import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from '@/components/sidebar/app-sidebar';
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Admin Section",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <SidebarProvider>
            <AppSidebar />
            <main>
                <SidebarTrigger className="text-2xl"/>
                {children}
            </main>
        </SidebarProvider>
    )
}